language: node_js
sudo: false
node_js:
   - "0.12"
   - "0.10"
script: "grunt $TEST_SUITE"
notifications:
   irc:
      channels: "chat.freenode.net#laxarjs"
      template: "%{repository_slug} (%{commit}) [%{branch}]: %{message}"
